name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the dev branch
  push:
    branches: [ AlertStormManagement ]
  pull_request:
    branches: [ AlertStormManagement ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Print working directory
        shell: powershell
        run: Get-ChildItem -recurse
