name: Publish Wiki

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publishWiki:

    # Specify the version of Windows
    runs-on: windows-latest

    # Only publish wiki when "main" is updated
    #if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout AlertManagement
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          path: 'managementPack'
      
      - name: Checkout Wiki
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}.wiki
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          path: 'wiki'

      - name: Copy Wiki Files
        shell: powershell
        run: |
          Remove-Item -Path .\wiki\* -Recurse
          Get-ChildItem -Path .\managementPack\WikiSource\ -Recurse | Copy-Item -Destination .\wiki\

      - name: Commit Wiki Changes
        shell: powershell
        run: |
          Set-Location -Path .\wiki\
          git config --global user.email "$env:GITHUB_ACTOR@users.noreply.github.com"
          git config --global user.name $env:GITHUB_ACTOR
          git add -A
          git commit -m 'Automatic Wiki Update'
          git push
