name: Publish Wiki

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  publishWiki:

    # Specify the version of Windows
    runs-on: windows-latest

    steps:
      - name: Checkout AlertManagement
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          path: 'managementPack'
        
      - name: Checkout Wiki
        uses: actions/checkout@v2
        with:
          repository: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY.wiki.git
          path: 'wiki'

      - name: Copy Wiki files
        shell: powershell
        run: |
          Remove-Item -Path .\wiki\* -Recurse
          Get-ChildItem -Path .\managementPack\WikiSource\* -Recurse | Copy-Item -Destination .\wiki\

      - name: Check In Wiki
        uses: EndBug/add-and-commit@v7
        with:
          add: './wiki'
          message: 'Updated Wiki'